[versions]
okhttp = "4.9.3"
coroutines = "1.6.0"
compose = "1.4.0"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
coroutines.core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines.android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx.core.ktx = { module = "androidx.core:core-ktx" }
androidx.lifecycle.runtime.ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx" }
androidx.activity.compose = { module = "androidx.activity:activity-compose" }
androidx.ui = { module = "androidx.compose.ui:ui" }
androidx.ui.graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx.ui.tooling.preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx.material3 = { module = "androidx.compose.material3:material3" }
